[package]
name = "genanki"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
uuid = { version = "1.0", feature = ["v4"] }
zip = "2.1.6"
sha1 = "0.10.6"
rusqlite = "0.32.1"
rand = "0.8.5"
chrono = "0.4.38"
sha2 = "0.10.8"